### PR TITLE
FRE-14 Initial docker setup

### PR DESCRIPTION
**Pull request by mclrc**
Should simplify deployment and testing, at the cost of some complexity in the configuration. I think this is very well worth it as it makes us much more flexible in terms of hosting providers and personal setups.

I also added `just`, which I really like for saving more complex shell commands for a project.

With this PR, `just test`, `just dev`, and `just prod` run the setup for testing, local development with hot-reload, and production respectively. `brew install just` should do the trick on Mac. You also need docker and docker compose. On Mac, you can just install docker desktop, which is kind of bloated but still gives a nice overview and simplifies setup.

I'd appreciate your feedback. The config files might look like a lot at first, I definitely recommend you look into docker if you haven't before, but it's quick to learn and we ideally shouldn't have to touch these files much.

I can't really set this up for production deployment as I don't know exactly how it works/don't have access. I think it will make deployment and maintenance a lot simpler though, especially once we have an ORM.

### CODE REVIEW

**Comment by johan-t** [comment]
@mclrc do you know why the tests are failing?

**Comment by mclrc** [comment]
@johan-t the db in the docker volume does not have the proper schema. I didn't look into how you set it up yet, lets have a chat today

**Review by johan-t — APPROVED** [review]
lgtm

**Comment by brandesdavid** [comment]
> Tested on linux, uses around 200MiB including `dockerd` and the two containers. @brandesdavid can our current droplet handle that?

Yes, our droplet has 2gb ram. 300mb is already used for backend.

**Comment by mclrc** [comment]
nice, then it's good to deploy from my side. the only important thing is making sure that docker + docker compose and just are available in the droplet, as well as the adjusted environment variables. i adjusted the readme accordingly :)

**Comment by johan-t** [comment]
> nice, then it's good to deploy from my side. the only important thing is making sure that docker + docker compose and just are available in the droplet, as well as the adjusted environment variables. i adjusted the readme accordingly :)

@brandesdavid can you check this?

**Comment by brandesdavid** [comment]
will check and add docker and docker compose

**Pull request merged**
